name: publish
concurrency: ${{ github.workflow }}-${{ github.ref }}
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: ğŸŸ¢ Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: ğŸŸ¢ Setup Node
        uses: actions/setup-node@v6
      - name: âš™ï¸ Install & build
        shell: bash
        run: |
          bun install
          bun run build
      - name: ğŸ”§ Setup Git User & Signing
        run: |
          git config user.name "${{ github.repository_owner }}"
          git config user.email "${{ github.repository_owner_id }}+${{ github.repository_owner }}@users.noreply.github.com"
      - name: ğŸ”§ Setup NPM
        run: |
          npm config set access public
          npm config set provenance true
      - name: ğŸš€ Create Pull Request & Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun changeset publish
          setupGitUser: false
          commit: "âœ… chore: update version"
          title: "âœ… chore: update version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
